FROM openjdk:8-jdk-alpine
MAINTAINER namanshukla801@gmail.com	
COPY /target/docker-k-hello-world-0.0.1-SNAPSHOT.jar naman0312/my-first-dk-image-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/naman0312/my-first-dk-image-0.0.1-SNAPSHOT.jar"]